"""empty message

Revision ID: 377a18d6445b
Revises: 973fdf47d7f9
Create Date: 2026-02-25 19:58:26.528261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377a18d6445b'
down_revision: Union[str, Sequence[str], None] = '973fdf47d7f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('category', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu', 'category')
    # ### end Alembic commands ###
