"""empty message

Revision ID: 973fdf47d7f9
Revises: 6aae93102e2b
Create Date: 2026-02-19 22:15:41.715984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973fdf47d7f9'
down_revision: Union[str, Sequence[str], None] = '6aae93102e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('description', sa.String(), nullable=True))
    op.add_column('menu', sa.Column('price', sa.Integer(), nullable=False))
    op.add_column('menu', sa.Column('in_stock', sa.Boolean(), nullable=False))
    op.drop_constraint(op.f('tables_user_id_fkey'), 'tables', type_='foreignkey')
    op.drop_column('tables', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tables', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tables_user_id_fkey'), 'tables', 'users', ['user_id'], ['id'])
    op.drop_column('menu', 'in_stock')
    op.drop_column('menu', 'price')
    op.drop_column('menu', 'description')
    # ### end Alembic commands ###
